# -*- coding: utf-8 -*-
"""
/***************************************************************************
 VegetationSeasonalStabilityIndex(vssi)
                                 A QGIS plugin
 Healthy forests exhibit stable seasonal vegetation cycles, while stressed ecosystems show abnormal intra-annual variability.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-03-10
        copyright            : (C) 2026 by Vishesh
        email                : vishesh.singhal@research.iiit.ac.in
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):
    from .vssi import VegetationSeasonalStabilityIndex
    return VegetationSeasonalStabilityIndex(iface)
